export const PRODUCTS_DETAIL = {
  'fm200-clean-agent-suppression-system': {
    name: 'FM200 Clean Agent Suppression System',
    brand: 'Kidde',
    category: 'Fire Protection',
    description:
      'The FM200 (HFC-227ea) clean agent suppression system is a fast-acting, non-corrosive fire suppression solution ideal for occupied spaces, data centres, server rooms, and critical equipment areas. It leaves no residue, causes no collateral damage, and is safe for use around people.',
    images: ['/images/product-fire-extinguisher.png'],
    modelSrc: null,
    isRender: true,
    specs: {
      Agent: 'HFC-227ea (FM200)',
      'Coverage Volume': 'Up to 200 m³',
      'Operating Pressure': '25 bar / 42 bar',
      'Discharge Time': '< 10 seconds',
      'Storage Temperature': '0°C to 54°C',
      Certification: 'UL Listed, FM Approved',
      Compliance: 'NFPA 2001, ISO 14520',
    },
    variants: [
      { name: 'Cylinder Capacity', options: ['25L', '50L', '80L', '120L', '180L'] },
      { name: 'Pressure Rating', options: ['25 bar', '42 bar'] },
    ],
    certifications: ['UL Listed', 'FM Approved', 'QCDD Compliant', 'NFPA 2001'],
  },
  'emergency-fire-equipment-cabinet': {
    name: 'Emergency Fire Equipment Cabinet',
    brand: 'Gloria',
    category: 'Fire Protection',
    description:
      'Steel-fabricated fire equipment cabinet for hose reels, extinguishers and emergency tools. Available in surface-mount or recessed installation with safety glass or acrylic glazing.',
    images: ['/images/product-fire-equipment.jpg'],
    modelSrc: null,
    isRender: false,
    specs: {
      Material: 'Powder-coated steel',
      'Door Configuration': 'Single / Double door',
      Glazing: 'Safety glass / Acrylic',
      'RAL Colour': 'Fire red RAL 3000',
      Mounting: 'Surface / Recessed',
      Compliance: 'BS 9999, QCDD',
    },
    variants: [
      { name: 'Cabinet Size', options: ['600×600 mm', '700×700 mm', '900×900 mm'] },
      { name: 'Door Type', options: ['Single Door', 'Double Door'] },
      { name: 'Glazing', options: ['Safety Glass', 'Acrylic'] },
    ],
    certifications: ['BS 9999', 'QCDD Compliant'],
  },
  'ceiling-cassette-fcu-4-way-blow': {
    name: 'Ceiling Cassette FCU — 4-Way Blow',
    brand: 'Daikin',
    category: 'HVAC',
    description:
      'Four-way blow ceiling cassette fan coil unit with 360° air distribution. Designed for commercial spaces with concealed installation for a clean aesthetic finish.',
    images: ['https://images.unsplash.com/photo-1718203862467-c33159fdc504?w=800&h=600&fit=crop&q=80'],
    modelSrc: null,
    isRender: false,
    specs: {
      'Air Distribution': '4-way',
      'Cooling Capacity Range': '2.2 – 14.0 kW',
      'Heating Capacity Range': '2.5 – 16.0 kW',
      Refrigerant: 'R-32',
      'Energy Rating': 'A+++',
      'Noise Level': '26–46 dB(A)',
      Compliance: 'ASHRAE 90.1',
    },
    variants: [
      { name: 'Capacity', options: ['2.2 kW', '3.5 kW', '5.6 kW', '7.1 kW', '9.0 kW', '14.0 kW'] },
      { name: 'Refrigerant', options: ['R-32', 'R-410A'] },
    ],
    certifications: ['CE Mark', 'ASHRAE Compliant', 'ISO 5151'],
  },
  'online-ups-system-10-kva': {
    name: 'Online UPS System 10 kVA',
    brand: 'APC by Schneider Electric',
    category: 'Electrical',
    description:
      'Double-conversion online UPS providing continuous power protection for critical loads. Zero transfer time ensures servers, network equipment, and medical devices remain protected at all times.',
    images: ['https://images.unsplash.com/photo-1555963966-b7ae5404b6ed?w=800&h=600&fit=crop&q=80'],
    modelSrc: null,
    isRender: false,
    specs: {
      Topology: 'Double conversion (online)',
      'Output Power': '10 kVA / 10 kW',
      'Transfer Time': '0 ms (zero transfer)',
      'Input Voltage': '220–240V AC ±15%',
      'Output Voltage': '230V AC ±2%',
      'Battery Backup': '8–15 minutes at full load',
      Communication: 'SNMP, USB, RS-232',
    },
    variants: [
      { name: 'Capacity', options: ['6 kVA', '10 kVA', '15 kVA', '20 kVA', '40 kVA'] },
      { name: 'Runtime', options: ['Standard', 'Extended (external battery)'] },
    ],
    certifications: ['UL Listed', 'CE Mark', 'IEC 62040'],
  },
  'armoured-electrical-cable-3-core': {
    name: 'Armoured Electrical Cable 3-Core',
    brand: 'Prysmian',
    category: 'Electrical',
    description:
      'XLPE-insulated steel wire armoured (SWA) power cable for underground and direct burial installations. Suitable for power distribution up to 1000V in industrial, commercial and infrastructure projects.',
    images: ['https://images.unsplash.com/photo-1585585825759-979ec75438cc?w=800&h=600&fit=crop&q=80'],
    modelSrc: '/models/electrical-cable.gltf',
    isRender: false,
    specs: {
      Insulation: 'XLPE (Cross-linked Polyethylene)',
      Armour: 'Steel Wire Armour (SWA)',
      Sheath: 'PVC outer sheath',
      'Voltage Rating': '0.6/1 kV (1000V)',
      'Conductor Material': 'Plain copper',
      Standard: 'BS 5467, IEC 60502-1',
      Installation: 'Underground, direct burial, duct',
    },
    variants: [
      { name: 'Cross Section', options: ['2.5 mm²', '4 mm²', '6 mm²', '10 mm²', '16 mm²', '25 mm²', '35 mm²', '50 mm²'] },
      { name: 'Core Count', options: ['3 Core', '4 Core', '5 Core'] },
    ],
    certifications: ['BS 5467', 'IEC 60502-1', 'CE Mark'],
  },
  'galvanized-steel-pipe-fitting-set': {
    name: 'Galvanized Steel Pipe Fitting Set',
    brand: 'Georg Fischer',
    category: 'Plumbing',
    description:
      'Hot-dip galvanized carbon steel threaded pipe fittings for potable water distribution, fire protection and industrial piping. BSP threaded connections, fully galvanized inside and out for superior corrosion resistance.',
    images: ['/images/product-pipe-fitting.png'],
    modelSrc: '/models/belt-drive.glb',
    isRender: true,
    specs: {
      Material: 'Carbon steel, hot-dip galvanized',
      'Thread Standard': 'BSP (BS 21)',
      'Pressure Rating': 'PN 16 (16 bar)',
      'Temperature Range': '-10°C to 120°C',
      Standard: 'BS 1387, EN 10255',
      Coating: 'Hot-dip galvanized (min. 45 µm)',
    },
    variants: [
      { name: 'Pipe Size', options: ['½"', '¾"', '1"', '1¼"', '1½"', '2"', '2½"', '3"', '4"'] },
      { name: 'Fitting Type', options: ['Elbow 90°', 'Elbow 45°', 'Tee Equal', 'Reducer', 'Coupling', 'Cap', 'Union'] },
    ],
    certifications: ['BS 1387', 'EN 10255', 'ISO 65', 'WRAS Approved'],
  },
  'ip-ptz-security-camera-4k': {
    name: 'IP PTZ Security Camera 4K',
    brand: 'Hikvision',
    category: 'LV Systems',
    description:
      '4K Ultra-HD pan-tilt-zoom IP network camera with 36× optical zoom, IR night vision up to 100m and intelligent motion tracking. Suitable for large-area surveillance in commercial, industrial and government facilities.',
    images: ['https://images.unsplash.com/photo-1688841747582-41097036109d?w=800&h=600&fit=crop&q=80'],
    modelSrc: null,
    isRender: false,
    specs: {
      Resolution: '4K (3840×2160)',
      'Optical Zoom': '36×',
      'IR Night Vision': 'Up to 100m',
      'Pan Range': '360° continuous',
      'Tilt Range': '-15° to 90°',
      'Network Protocol': 'TCP/IP, HTTP, RTSP, ONVIF',
      Power: 'PoE+ (802.3at) / 24V AC',
    },
    variants: [
      { name: 'Resolution', options: ['2MP (1080p)', '4MP', '8MP (4K)'] },
      { name: 'Optical Zoom', options: ['16×', '25×', '36×'] },
    ],
    certifications: ['CE Mark', 'FCC', 'ONVIF Profile S/G/T'],
  },
  'pressure-gauge-testing-kit': {
    name: 'Pressure Gauge & Testing Kit',
    brand: 'WIKA',
    category: 'Plumbing',
    description:
      'Precision pressure testing kit for commissioning water, gas and fire suppression systems. Includes calibrated gauges, fittings and test records for QCDD and consultant acceptance.',
    images: ['https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&h=600&fit=crop&q=80'],
    modelSrc: null,
    isRender: false,
    specs: {
      'Pressure Range': '0–600 bar (gauge selection)',
      'Accuracy Class': '0.6 / 1.0 / 1.6',
      'Dial Size': '63 mm / 100 mm / 160 mm',
      Connection: 'BSP / NPT ¼" to 1"',
      'Wetted Parts': 'Stainless steel, brass',
      Standard: 'EN 837-1, ASME B40.100',
    },
    variants: [
      { name: 'Pressure Range', options: ['0–10 bar', '0–16 bar', '0–25 bar', '0–40 bar', '0–60 bar', '0–100 bar'] },
      { name: 'Dial Size', options: ['63 mm', '100 mm', '160 mm'] },
    ],
    certifications: ['EN 837-1', 'ASME B40.100'],
  },
  'vrf-outdoor-condensing-unit-8hp': {
    name: 'VRF Outdoor Condensing Unit 8HP',
    brand: 'Mitsubishi Electric',
    category: 'HVAC',
    description:
      "Variable Refrigerant Flow (VRF) outdoor condensing unit rated at 8HP for multi-zone commercial cooling. Suitable for offices, hotels and retail environments in Qatar's climate. Energy-efficient inverter compressor with R-32 refrigerant.",
    images: ['https://images.unsplash.com/photo-1563166423-482a8c14b2d6?w=800&h=600&fit=crop&q=80'],
    modelSrc: null,
    isRender: false,
    specs: {
      Capacity: '22.4 kW (8HP)',
      Refrigerant: 'R-32',
      'Compressor Type': 'Variable-speed inverter scroll',
      'Connected Indoor Units': 'Up to 13 indoor units',
      'Piping Length': 'Up to 165 m total / 90 m per branch',
      'Power Supply': '3-phase, 380V / 50 Hz',
      'Noise Level': '58 dB(A)',
      'Energy Rating': 'SEER 8.5 / COP 4.1',
      Compliance: 'ASHRAE 90.1, QCDD MEP Code',
    },
    variants: [
      { name: 'Capacity', options: ['4HP', '6HP', '8HP', '10HP', '14HP', '20HP'] },
      { name: 'Refrigerant', options: ['R-32', 'R-410A'] },
    ],
    certifications: ['CE Mark', 'ASHRAE Compliant', 'ISO 5151', 'Gulf Approved'],
  },
  'access-control-intercom-panel': {
    name: 'Access Control & Intercom Panel',
    brand: 'Honeywell',
    category: 'LV Systems',
    description:
      'Integrated access control and IP video intercom panel for commercial and residential buildings. Supports card, PIN and biometric entry with remote management via cloud-based software. QCDD and GRMS compliant for Qatar government projects.',
    images: ['https://images.unsplash.com/photo-1718203862467-c33159fdc504?w=800&h=600&fit=crop&q=80'],
    modelSrc: null,
    isRender: false,
    specs: {
      Authentication: 'RFID card, PIN, fingerprint, face recognition',
      Communication: 'TCP/IP, RS-485, Wiegand 26/34',
      'Video Resolution': '2MP (1920×1080) HD',
      'Night Vision': 'IR up to 3 m',
      'Door Relay': '2 × NO/NC relay, 3A',
      Memory: 'Up to 100,000 cards / events',
      'Management Software': 'WIN-PAK cloud / on-premise',
      Power: 'PoE (802.3af) / 12V DC',
      Compliance: 'CE, FCC, SBD, BS EN 60839-11',
    },
    variants: [
      { name: 'Authentication', options: ['Card Only', 'Card + PIN', 'Card + Biometric', 'Multi-factor'] },
      { name: 'Installation', options: ['Surface mount', 'Flush mount'] },
    ],
    certifications: ['CE Mark', 'FCC', 'SBD Approved', 'BS EN 60839'],
  },
};
